[package]
name = "kubyl_operators"
description = "OLM operators, OperatorHub and Helm releases."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
gpui.workspace = true
kubyl_core.workspace = true
