[package]
name = "kubyl_portforward"
description = "Port-forward manager."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
gpui.workspace = true
kubyl_core.workspace = true
